name: Lint
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".golangci.yml"
      - ".github/workflows/lint.yml"
  workflow_dispatch:

jobs:
  resolve-modules:
    name: resolve module
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - id: set-matrix
        run: ./.hack/resolve-modules.sh

  lint:
    name: lint module
    runs-on: ubuntu-latest
    needs: resolve-modules
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: ${{ matrix.workdir }}
