name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        go: [ 1.23.x ]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      - name: Generate CHANGELOG
        run: |
          github_changelog_generator --user ${GITHUB_REPOSITORY_OWNER} --project ${GITHUB_REPOSITORY#*/} \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --since-tag $(git describe --tags --abbrev=0 --match "v*.*.*" `git rev-list --tags --skip=1 --max-count=1`) \
          --future-release ${GITHUB_REF_NAME}

      - name: Commit CHANGELOG
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for ${GITHUB_REF_NAME}" || echo "No changes to commit"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body_path: CHANGELOG.md
